' Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <https://www.gnu.org/licenses/>.

' Preview durch <Alt>d

@startuml Anwendungskern

interface Promise<T>

package @nestjs/common {
  class "@Injectable" as Injectable
  hide Injectable circle
}

package typeorm {
  class Repository<T>
}

package @nestjs/typeorm {
  class "@InjectRepository" as InjectRepository
  hide InjectRepository circle
}

package mail {
  class MailService
}

package monitor {
  package entity {
    class Monitor
  }

  package service #DDDDDD {
    class MonitorInvalid
    class NameExists
    class VersionInvalid
    class VersionOutdated

    class MonitorWriteService << control >> <<@Injectable()>> {
      + async create(monitor: Monitor): Promise<string|MonitorInvalid|NameExists>
      + async update(id: string, monitor: Monitor, version: string): Promise<number|MonitorInvalid|NameExists|VersionInvalid|VersionOutdated>
      + async delete(id: string): Promise<boolean>
    }

    MonitorWriteService o--> "1" MonitorValidationService: validationService
    MonitorWriteService o--> "1" MonitorReadService: readService
    MonitorWriteService o--> "1" Repository: @InjectRepository repo
    MonitorWriteService o--> "1" MailService: mailService

    MonitorWriteService .up.> Injectable
    MonitorWriteService .up.> InjectRepository

    MonitorWriteService .up.> Promise
    MonitorWriteService ..> Monitor
    MonitorWriteService .up.> MonitorInvalid
    MonitorWriteService .up.> NameExists
    MonitorWriteService .up.> VersionInvalid
    MonitorWriteService .up.> VersionOutdated

    MonitorInvalid .up[hidden].> Monitor
    Monitor .up[hidden].> Promise
    Monitor .up[hidden].> Injectable
    Monitor .up[hidden].> InjectRepository
    NameExists .up[hidden].> Monitor
    MonitorValidationService .[hidden].> Repository
    MonitorValidationService .[hidden].> MailService
  }
}

hide empty members

footer (c) Jürgen Zimmermann

@enduml
