// Copyright (C) 2020 - present Juergen Zimmermann, Hochschule Karlsruhe
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//
// N e t z w e r k   -   V e r b i n d u n g   n o t w e n d i g
//

// siehe auch https://studio.apollographql.com/sandbox/explorer

### Suche id, name, art und version von allen Monitoren
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{
  monitore {
    id
    name
    refreshrate
    version
  }
}

### Suche name, refreshrate, hersteller und version von einem Monitor mit vorhandener Monitor-ID
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query ($id: ID! = "00000000-0000-0000-0000-000000000001") {
  monitor(id: $id) {
    name
    refreshrate
    hersteller
    version
  }
}

{
  "id": "00000000-0000-0000-0000-000000000001"
}

### Suche name von einem Monitor mit nicht-vorhandener Monitor-ID
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query ($id: ID! = "99999999-9999-9999-9999-999999999999") {
  monitor(id: $id) {
    name
  }
}

{
  "id": "99999999-9999-9999-9999-999999999999"
}

### Suche refreshrate von Monitoren mit vorhandenem Titel
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query ($name: String = "Alpha") {
  monitore(name: $name) {
    refreshrate
  }
}

{
  "name": "Alpha"
}

### Suche name, art und schlagwoerter von Monitoren mit vorhandenem Titel
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query ($name: String = "a") {
  monitore(name: $name) {
    name
    art
    schlagwoerter
  }
}

{
  "name": "a"
}

### Suche refreshrate von Monitoren mit NICHT-vorhandenem Titel
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query ($name: String = "Nichtvorhanden") {
  monitore(name: $name) {
    refreshrate
  }
}

{
  "name": "Nichtvorhanden"
}
