// Copyright (C) 2020 - present Juergen Zimmermann, Hochschule Karlsruhe
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//
// N e t z w e r k   -   V e r b i n d u n g   n o t w e n d i g
//

### Einloggen in der Rolle "admin", "mitarbeiter" und "kunde"
// @name login
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  login(username: "admin", password: "p") { token expiresIn roles }
}

### Einloggen in der Rolle "mitarbeiter" und "kunde"
// @name login
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  login(username: "alfred.alpha", password: "p") { token expiresIn roles }
}

### Einloggen in der Rolle "kunde"
// @name login
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  login(username: "dirk.delta", password: "p") { token expiresIn roles }
}

### Einloggen mit falschem Passwort
// @name login
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  login(username: "admin", password: "FALSCH") { token expiresIn roles }
}

### Neuen Monitor anlegen
POST {{graphQlUrl}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.login.token}}
X-REQUEST-TYPE: GraphQL

mutation {
  create(
    input: {
      name: "MonGraphQL",
      hersteller: "HerGraphQL",
      preis: 99.9,
      bestand: 2,
      curved: true,
      refreshRate: "Hz60",
      release: "2022-01-31",
      schlagwoerter: ["highres"]
    }
  )
}

### Neuen Monitor mit ungueltigen Daten anlegen
POST {{graphQlUrl}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.login.token}}
X-REQUEST-TYPE: GraphQL

mutation {
  create(
    input: {
      name: "???",
      hersteller: "!!!",
      preis: -999,
      bestand: 0.1,
      curved: true,
      refreshRate: "61",
      release: "123",
      schlagwoerter: ["highres"]
    }
  )
}

### Vorhandenes Monitor aktualisieren
POST {{graphQlUrl}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.login.token}}
X-REQUEST-TYPE: GraphQL

mutation {
  update(
    input: {
      id: "00000000-0000-0000-0000-000000000003",
      name: "ChngMonGraphQL",
      hersteller: "ChngHerGraphQL",
      preis: 77.7,
      bestand: 7,
      curved: true,
      refreshRate: "Hz120",
      release: "2022-02-02",
      schlagwoerter: ["highres"]
    }
  )
}

### Vorhandenes Monitor mit ungueltigen Werten aktualisieren
POST {{graphQlUrl}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.login.token}}
X-REQUEST-TYPE: GraphQL

mutation {
  update(
    input: {
      id: "00000000-0000-0000-0000-000000000003",
      name: "???",
      hersteller: "!!!",
      preis: -800,
      bestand: 9.8,
      curved: true,
      refreshRate: "123",
      release: "321",
      schlagwoerter: ["highres"]
    }
  )
}

### Nicht-Vorhandenes Monitor aktualisieren
POST {{graphQlUrl}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.login.token}}
X-REQUEST-TYPE: GraphQL

mutation {
  update(
    input: {
      id: "99999999-9999-9999-9999-999999999999",
      name: "ChngMonGraphQL",
      hersteller: "ChngHerGraphQL",
      preis: 77.7,
      bestand: 7,
      curved: true,
      refreshRate: "Hz120",
      release: "2022-02-02",
      schlagwoerter: ["highres"]
    }
  )
}

### Vorhandenes Monitor loeschen
POST {{graphQlUrl}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.login.token}}
X-REQUEST-TYPE: GraphQL

mutation {
  delete(id: "00000000-0000-0000-0000-000000000060")
}
